Exercise Set for Creating Arrays 

 Create a NumPy array of size 8 filled with zeros.
 Generate a NumPy array containing the numbers from 10 to 50.
 Create a 3x3 matrix with values ranging from 0 to 8.

In [3]:
import numpy as np

Zero_arr = np.zeros(8)
print(Zero_arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
import numpy as np

range_arr = np.arange(10, 51)
print(range_arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [4]:
import numpy as np

matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Exercise Set for Array Indexing and Slicing 

 Extract the third element from the array created in Exercise 2.
 From the matrix in Exercise 3, retrieve the second row.
 Create a 4x4 matrix and use slicing to obtain the first two rows and last two columns.

In [5]:
import numpy as np

range_arr  = np.arange(10, 51)
third_element = range_arr [2]
print(third_element)

12


In [6]:
import numpy as np

matrix = np.arange(0, 9).reshape(3, 3)
second_row = matrix[1]

print(second_row)

[3 4 5]


In [7]:
import numpy as np

# Create a 4x4 matrix
matrix = np.arange(16).reshape(4, 4)
print("Original matrix:")
print(matrix)

Original matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [8]:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

In [10]:
print(first_two_rows_last_two_cols = [row[2:] for row in matrix[:2]])

TypeError: 'first_two_rows_last_two_cols' is an invalid keyword argument for print()

 Exercise Set for Data Types 

 Create an array with the elements [1.1, 2.2, 3.3] and convert them into integers.
 Define an array with the elements ["1", "2", "3"] and convert them into floats.

In [11]:
import numpy as np

# Create the array with float values
arr = np.array([1.1, 2.2, 3.3])
print("Original array:", arr)

# Convert the array to integers
int_arr = arr.astype(int)
print("Integer array:", int_arr)

Original array: [1.1 2.2 3.3]
Integer array: [1 2 3]


In [12]:
import numpy as np

# Create the array with string elements
arr = np.array(["1", "2", "3"])
print("Original array:", arr)

# Convert the array to floats
float_arr = arr.astype(float)
print("Float array:", float_arr)

Original array: ['1' '2' '3']
Float array: [1. 2. 3.]


 Exercise Set for Copy vs View
 
 Create an array of five random numbers. Make a copy of this array and change the first element of the original array. Print both arrays.
 Create an array of five random numbers. Create a view of this array and change the first element of the view. Print both arrays.

In [14]:
a = np.array([1, 2, 3,4,5])
b = a. copy ()
b[0] = 10
print(a) 

[1 2 3 4 5]


In [15]:
print(b)

[10  2  3  4  5]


In [16]:
c = a.view()
c[0]=11
print(a)

[11  2  3  4  5]


In [17]:
print(c)

[11  2  3  4  5]


Exercise Set for Array Shape and Reshape

 Create a 2x6 matrix and reshape it into 3x4.
 Create an array of 12 random numbers and reshape it into a 3D array of dimensions 2x2x3

In [21]:
a = np.array ([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
print(a.shape)


(2, 6)


In [22]:
reshaped_a = a. reshape (3, 4)
print (reshaped_a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


 Exercise Set for Array Iterating 

 Create a 3x3 matrix and print each element using a nested loop.
 Using np.nditer, iterate over the 3D array created in Exercise 12 and print each element.

In [23]:
a = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
for row in a:
   for item in row:
     print (item)


1
2
3
3
4
5
6
7
8


In [25]:

c = np.array([[1, 2, 31],  [4, 5, 611]])
for x in np.nditer(c):
  print (x)

1
2
31
4
5
611


Exercise Set for Array Join 
• Create two 1D arrays of different sizes and concatenate them.
 • Create two 2D arrays and vertically stack them.

In [26]:
a1=np.array([1, 2, 3])
a2=np.array([4, 5, 6])
a3=np.concatenate((a1, a2))
print(a3)


[1 2 3 4 5 6]


In [29]:
a1=np.array([1, 2, 3])
a2=np.array([4, 5, 6])
a4=np.stack((a1, a2), axis=1)
print(a4)

[[1 4]
 [2 5]
 [3 6]]


 Exercise Set for Array Split 
• Create an array of 10 elements and split it into 3 arrays.
 • Create a 4x4 matrix and horizontally split it into 2 equal parts

In [30]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
new_arrays=np.array_split(a,3)
print(new_arrays)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


In [33]:
b=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12],[13, 14, 15, 16]])
hsplit_result=np.hsplit(b,2)
print(hsplit_result)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


 Exercise Set for Array Search 
• Create an array of 10 elements. Use np.whereto find indices of all elements greater than 5.
 • Create an array and use np.nonzeroto find all non-zero elements.

In [35]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
result=np.where(a>5)
print(result)

(array([5, 6, 7, 8, 9], dtype=int64),)


In [36]:
b=np.array([1, 0, 3, 4, 5, 0, 7, 0, 9, 10])
result=np.nonzero(b)
print(result)

(array([0, 2, 3, 4, 6, 8, 9], dtype=int64),)


Exercise Set for Array Sort 
• Create a random array of 10 elements and sort it in ascending order.
 • Create a 3x3 matrix and sort each row in descending order.

In [37]:
a=np.array([1, 0, 3, 4, 5, 0, 7, 0, 9, 10])
a.sort()
print(a)

[ 0  0  0  1  3  4  5  7  9 10]


In [40]:
a = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
a.sort( axis=1)
print(b)

[ 1  0  3  4  5  0  7  0  9 10]


Exercise Set for Array Filter 
• Create an array of 15 elements from 1 to 15. Use boolean indexing to filter out all odd numbers.
 • Given an array [1, 2, 3, 4, 5, 6], create a filter array that will return only elements greater than 3.

In [41]:
# Create an array of 15 elements from 1 to 15
arr = np.arange(1, 16)
print("Original array:", arr)

# Filter out odd numbers using boolean indexing
even_arr = arr[arr % 2 == 0]
print("\nArray with only even numbers:", even_arr)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Array with only even numbers: [ 2  4  6  8 10 12 14]


In [43]:
# Create the original array
arr = np.array([1, 2, 3, 4, 5, 6])

# Create the filter array
filter_arr = arr > 3

# Apply the filter to the original array
result = arr[filter_arr]



print("Filtered result:", result)

Filtered result: [4 5 6]


Exercise Set for Random 
• Use NumPy to generate an array of 15 random integers from 1 to 100.
 • Generate a 3x3 matrix with random floats between 0 to 1.

In [44]:
random_array = np.random.randint(1, 101, size=15)
print(random_array)

[ 48 100  21  44  65  72  80   8  87  69  44   1  85  24  90]


In [45]:
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(random_matrix)

Random 3x3 matrix:
[[0.23864012 0.10814058 0.28423222]
 [0.18028212 0.26461776 0.52097316]
 [0.91468051 0.52427209 0.76145067]]


 Exercise Set for Operations and Broadcasting 
• Create two arrays of the same shape and perform element-wise addition.
 • Create an array of shape (4,) and another of shape (4,1). Use broadcasting to add these two arrays.


In [48]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])


result = array1 + array2

print("Element-wise addition:")
print(result)

Element-wise addition:
[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [50]:
arr1 = np.array([1, 2, 3, 4])
print("Array 1:", arr1)
result = arr1 + arr2
print("Result:", result)

Array 1: [1 2 3 4]
Result: [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
